From: David Paleino <dapal@debian.org>
Subject: fix handling of resolv.conf when it's a symlink
Forwarded: not-needed
Origin: upstream
Bug-Debian: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691973

---
 wicd/wicd-daemon.py |   14 ++++++++++++--
 1 file changed, 12 insertions(+), 2 deletions(-)

--- wicd.orig/wicd/wicd-daemon.py
+++ wicd/wicd/wicd-daemon.py
@@ -1703,7 +1703,11 @@ def main(argv):
         # don't back up if .orig exists, probably there cause
         # wicd exploded
         if not os.path.exists(backup_location):
-            shutil.copy2('/etc/resolv.conf', backup_location)
+            if os.path.islink('/etc/resolv.conf'):
+                dest = os.readlink('/etc/resolv.conf')
+                os.symlink(dest, backup_location)
+            else:
+                shutil.copy2('/etc/resolv.conf', backup_location)
             os.chmod(backup_location, 0644)
     except IOError:
         print 'error backing up resolv.conf'
@@ -1750,7 +1754,13 @@ def main(argv):
 
         # restore resolv.conf on quit
         try:
-            shutil.move(wpath.varlib + 'resolv.conf.orig', '/etc/resolv.conf')
+            backup_location = wpath.varlib + 'resolv.conf.orig'
+            if os.path.islink(backup_location):
+                dest = os.readlink(backup_location)
+                os.remove('/etc/resolv.conf')
+                os.symlink(dest, '/etc/resolv.conf')
+            else:
+                shutil.move(backup_location, '/etc/resolv.conf')
             os.chmod('/etc/resolv.conf', 0644)
         except IOError:
             print 'error restoring resolv.conf'
